=head1 NAME

Text::MediaWiki::Parser - MediaWiki source text parser

=head1 XXX

XXX

=head1 SEE ALSO

Help:Contents <http://www.mediawiki.org/wiki/Help:Contents>.

Help:Formatting <http://www.mediawiki.org/wiki/Help:Formatting>.

Help:Links <http://www.mediawiki.org/wiki/Help:Links>.

Help:Categories <http://www.mediawiki.org/wiki/Help:Categories>.

Help:Lists <http://www.mediawiki.org/wiki/Help:Lists>.

Help:Images <http://www.mediawiki.org/wiki/Help:Images>.

Help:Tables <http://www.mediawiki.org/wiki/Help:Tables>.

Extension:Cite/Cite.php
<http://www.mediawiki.org/wiki/Extension:Cite/Cite.php>.

Help:Wiki markup <http://en.wikipedia.org/wiki/Help:Wiki_markup>.

Help:Section <http://en.wikipedia.org/wiki/Help:Section>.

Help:Magic words <http://www.mediawiki.org/wiki/Help:Magic_words>.

=cut
