=head1 NAME

Text::MediaWiki::Parser - MediaWiki source text parser

=head1 XXX

XXX

=head1 SEE ALSO

Help:Formatting <http://www.mediawiki.org/wiki/Help:Formatting>.

Help:Links <http://www.mediawiki.org/wiki/Help:Links>.

Help:Lists <http://www.mediawiki.org/wiki/Help:Lists>.

Help:Images <http://www.mediawiki.org/wiki/Help:Images>.

Extension:Cite/Cite.php
<http://www.mediawiki.org/wiki/Extension:Cite/Cite.php>.

Help:Wiki markup <http://en.wikipedia.org/wiki/Help:Wiki_markup>.

Help:Section <http://en.wikipedia.org/wiki/Help:Section>.

=cut
